# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: objective-c
podfile: Example/Podfile
cache: cocoapods

before_install: travis_wait pod repo update --silent

script: cd Example ; set -o pipefail && xcodebuild test -workspace 'RxAppState.xcworkspace' -scheme 'RxAppState-Example' -configuration 'Debug' -sdk iphonesimulator -destination platform='iOS Simulator',OS='12.0',name='iPhone SE' build test | xcpretty -c --test
