source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'RxAppState_Example' do
    pod 'RxAppState', :path => '../'

    target 'RxAppState_ExampleTests' do
        inherit! :search_paths
    end
end

pod 'RxSwift', :inhibit_warnings => true
pod 'RxCocoa', :inhibit_warnings => true

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.2'
        end
    end
end
