language: objective-c
osx_image: xcode10.1
os: osx
cache:
  directories:
    - Carthage
before_install:
  - gem install xcpretty-travis-formatter
  - curl -L -O https://github.com/YPlan/CartfileDiff/releases/download/0.1/CartfileDiff.pkg
  - sudo installer -pkg CartfileDiff.pkg -target /
script:
  - sh scripts/ci.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
