#!/bin/sh
SCRIPT_DIR=$(dirname "$0")
BOOTSTRAP="$SCRIPT_DIR/bootstrap"
CACHED_CARTFILE="Carthage/Cartfile.resolved"
if [ -e "$CACHED_CARTFILE" ]; then
  if ! cmp -s "$CACHED_CARTFILE" Cartfile.resolved
  then
    echo "Bootstrapping dependencies because Cartfile changed"
    "$BOOTSTRAP"
  else
    echo "Cartfile.resolved matches cached, skipping bootstrap"
  fi
else
  echo "Cached Cartfile.resolved not found, bootstrapping all dependencies"
  "$BOOTSTRAP"
fi
cp Cartfile.resolved Carthage
